name: Package Extension for Firefox 

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  package-extension:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Remove unnecessary files
        run: |
          rm -rf .git
          rm -rf .github
          rm -f cliff.toml

      - name: Remove Chrome's manifest.json entries
        run: |
          sed -i '/"service_worker": "scripts\/worker.js",/d' manifest.json

      # get version number from release or default to manual
      - name: Set version
        id: vars
        run: |
          if [ -n "${{ github.event.release.tag_name }}" ]; then
            echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "VERSION=manual" >> $GITHUB_ENV
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: elecord-extension-${{ env.VERSION }}_firefox
          path: .
